questions = {
    0: (10, '[img/DimentionsMC.png](900x400) W Vanilla Minecraft są 3 wymiary: overworld, nether, end. Wiadomo, że w netrze 1 blok odpowiada 8 blokom w overworld. Ilu blokom odpowiada 1 blok w endzie?', 'Nie ma takiego przelicznia.'),
    1: (20, 'W R6S ile operatorów ma umiejętności lecznicze (potrafi odnowić hp)(nie licząc Rook\'a)', '3 opertorów: Doc, ThunderBird, Finka'),
    2: (80, '[img/beholder.png](800x450)W grze Beholder. Carl Stein (główny protagonista) ile ma dzieci?', '2-oje Martha i Patrick'),
    3: (40, '[img/rocketLeague.png](850x400) Wymień wszystkie powerupy w rumble Rocket League?', 'But, kolce, zamrożenie, turbo, grappling hook, rękawica, pięść, magnet, ssawka, zamiana, tornado'),
    6: (100, '[img/Little_Sister.png](365x430) W Bioshock, co robią Little Sisters?', 'Chodzą po mapie i zbierają, z trupów, ADAM (serum takie) do strzykawki. Następnie konsumują ów ADAM i przez to przekształcają go na użyteczną formę.'),
    5: (40, '[img/alienIsolation.jpg](850x450) Jak nazywa się główna bohaterka Alien Isolation (imie i nazwisko)?', 'Amanda Ripley'),
    4: (30, 'W kim zakochał sie Jackie Wells? (Cyberpunk)', 'Misty Olszewski'),
    7: (20, 'Co w Minecraft w patch notes jest stale próbowane usunąć?', 'Herobrine'),
    8: (10, 'Na podstawie czego (inspiracja do sprite) zostały stworzone postacie w grze Satisfactory', 'Pszczół'),
    9: (50, 'Wymień prawidłowo numery przynajmniej 2-wu z 5 podanych SCP: Mrugacz, Nieśmiałek, Łazarz, Doktor Plaga, Ulepszarka', 'SCP-173: Mrugacz\nSCP-096: Nieśmiałek\nSCP-106: Łazarz\nSCP-049: Doktor Plaga\nSCP-914: UClockwork Machine'),
    10: (20, 'Jak nazywa się statek ratunkowy zesztrzelony przez wielkie działo w Subnautice.', 'Sunbeam'),
    11: (70, 'Wymień 2 z 4 zamontowanych rdzeni Glados w Portal 1', 'Morality, Curiosity, Intelligence, Anger'),
    12: (0, '', ''),
    13: (30, 'Wymień 20 NPC z Terrari.', 'Angler, Arms Dealer, Clothier, Demonolitionist, Dryad, Dye Trader, Goblin Tinkerer, Golfer, Guide, Mechanic, Merchant, Nurse, Old Man, Painter, Party Girl, Skeleton Merchant, Stylist, Tavernkeeper, Traveling Merchant, Witch Doctor, Zoologist, Cyborg, Pirate, Princess, Santa CLause, Steampunker, Tax Collector, Truffle, Wizard.'),
    14: (25, 'Jak nazywa się jedyny pracownik, który wiadomo że przetrwał neurotoksyny wysłane przez Glados i pozostawiał wiadomości w grze.', 'RatMan'),
    15: (70, 'Rozszerz tytuły gier z serii The Elder Scrolls (1-5)(można się raz pomylić).', 'The Elder Scrolls 1: Arena\nThe Elder Scrolls 2: Daggerfall\nThe Elder Scrolls 3: Morrowind\nThe Elder Scrolls 4: Oblivion\nThe Elder Scrolls 4: Oblivion'),
    16: (50, 'Wymień imona lub nazwiska 2z3ch głównych antagonistów FarCry3.', 'Vaas Montenegro, Hoyt Volker, Buck Hughes'),
    17: (20, 'Jak się nazywa tytan głównego bohatera z gry Titanfall 2, pełna nazwa daje +20p', 'BT-7274'),
    18: (100, 'Którą z podanych postaci z serii COD dubbinguje Garry Oldman: Captain Price, Sgt. John Soap MacTavish, Sgt. Viktor Reznov, Special Agent Jason Hudson', 'Sgt. Viktor Reznov'),
    19: (25, 'Jakiego wyboru dokonuje gracz na początku Dishonored 2 i pomiędzy czym wybiera?', 'Wyboru postaci. Wybiera czy będzie grać Emily czy Corvo'),
    20: (30, 'Jak się nazywa ostatnia misja w GTA V jeśli się wybierze by zabić Trevora?', 'Something Sensible'),
    21: (50, 'Gdzie dzieje się akcja Fallout 1?', 'Southern California'),
    22: (20, 'Jak się nazywa i czym jest pupil Doom Guya/ Doom Slayera', 'Królik Daisy'),
    23: (70, 'Kto otworzył portal do piekła w Doom? (Pełna nazwa +20p)', 'The UAC (Union Aerospace Corporation)'),
    24: (25, 'Jak się nazywa główny antagonista Borderlands 2?', 'Handsome Jack'),
}


# 900x400
